replicaCount: 2

image:
  repository: your-dockerhub-username/flask-redis-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

redis:
  image: redis:alpine
  port: 6379
